const CarouselData = [
    {
       'id':1,
       'image':'/images/arduino.jpg',
       'leftTitle':'EVENT',
       'rightTitle':'events'
    },
    {
        'id':2,
        'image':'./images/arduino.jpg',
        'leftTitle':'EVENT',
        'rightTitle':'events'
     },
     {
        'id':3,
        'image':'./images/arduino.jpg',
        'leftTitle':'EVENT',
        'rightTitle':'events'
     },
     {
        'id':4,
        'image':'./images/arduino.jpg',
        'leftTitle':'EVENT',
        'rightTitle':'events'
     },
     {
        'id':5,
        'image':'./images/arduino.jpg',
        'leftTitle':'EVENT',
        'rightTitle':'events'
     },
     {
        'id':6,
        'image':'./images/arduino.jpg',
        'leftTitle':'EVENT',
        'rightTitle':'events'
     },
     {
        'id':7,
        'image':'./images/arduino.jpg',
        'leftTitle':'EVENT',
        'rightTitle':'events'
     },
     {
        'id':8,
        'image':'./images/arduino.jpg',
        'leftTitle':'EVENT',
        'rightTitle':'events'
     },
     {
        'id':9,
        'image':'./images/arduino.jpg',
        'leftTitle':'EVENT',
        'rightTitle':'events'
     },
     {
        'id':10,
        'image':'./images/arduino.jpg',
        'leftTitle':'EVENT',
        'rightTitle':'events'
     }
]

export default CarouselData